#pragma once

/* Generated by cbindgen from crates/emulator-ffi. Do not edit by hand; regenerate with rewinds-ios/build-core.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * GBA.
 */
#define REWINDS_CONSOLE_GBA 0

/**
 * Nintendo DS.
 */
#define REWINDS_CONSOLE_NDS 1

/**
 * Success.
 */
#define REWINDS_OK 0

/**
 * No console given and none detectable from the ROM header.
 */
#define REWINDS_ERR_UNKNOWN_CONSOLE 1

/**
 * The GBA requires a BIOS image and none was supplied.
 */
#define REWINDS_ERR_MISSING_BIOS 2

/**
 * The console is recognised but not implemented.
 */
#define REWINDS_ERR_UNSUPPORTED 3

/**
 * A `.nds` image could not be booted.
 */
#define REWINDS_ERR_BAD_IMAGE 4

/**
 * A null argument where one was required.
 */
#define REWINDS_ERR_NULL -1

/**
 * Guest code panicked while booting.
 */
#define REWINDS_ERR_PANIC -2

#define REWINDS_BTN_A (1 << 0)

#define REWINDS_BTN_B (1 << 1)

#define REWINDS_BTN_SELECT (1 << 2)

#define REWINDS_BTN_START (1 << 3)

#define REWINDS_BTN_RIGHT (1 << 4)

#define REWINDS_BTN_LEFT (1 << 5)

#define REWINDS_BTN_UP (1 << 6)

#define REWINDS_BTN_DOWN (1 << 7)

#define REWINDS_BTN_R (1 << 8)

#define REWINDS_BTN_L (1 << 9)

#define REWINDS_BTN_X (1 << 10)

#define REWINDS_BTN_Y (1 << 11)

/**
 * An opaque audio-consumer handle, drained by the host's audio thread. The pointer
 * addresses a boxed [`AudioSource`]; see [`RewindsEmulator`] for the idiom.
 */
typedef struct RewindsAudio RewindsAudio;

/**
 * An opaque emulator handle. Built by [`rewinds_load`], freed by [`rewinds_destroy`].
 *
 * The pointer the host holds actually addresses a boxed [`Emulator`]; this marker
 * only gives that pointer a distinct C type (cbindgen forward-declares it). `Emulator`
 * is not `#[repr(C)]`, so it never crosses the boundary by value — the classic opaque
 * handle idiom. The `[u8; 1]` field is inert: the pointer is never dereferenced as a
 * `RewindsEmulator`, only cast back to `Emulator`.
 */
typedef struct RewindsEmulator RewindsEmulator;

/**
 * What to boot. Mirrors [`emulator::Load`] with raw pointers: each `*_len` of `0`
 * (or a null pointer) means "absent". `console` is `-1` to auto-detect, `0` GBA,
 * `1` NDS.
 */
typedef struct {
    int32_t console;
    const uint8_t *rom;
    uintptr_t rom_len;
    const uint8_t *bios;
    uintptr_t bios_len;
    const uint8_t *bios7;
    uintptr_t bios7_len;
    const uint8_t *firmware;
    uintptr_t firmware_len;
} RewindsLoad;

/**
 * A presentable screen: `width * height` RGBA8 pixels at `rgba` (`len` bytes),
 * borrowed from the emulator and valid only until the next mutating call.
 */
typedef struct {
    uint32_t width;
    uint32_t height;
    const uint8_t *rgba;
    uintptr_t len;
} RewindsScreen;

/**
 * A borrowed byte span handed out by the core (e.g. [`rewinds_save_data`]), valid
 * only until the next mutating call.
 */
typedef struct {
    const uint8_t *ptr;
    uintptr_t len;
} RewindsBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Detect the console from a ROM header: [`REWINDS_CONSOLE_GBA`],
 * [`REWINDS_CONSOLE_NDS`], or `-1` if neither matches (the host can still force one).
 *
 * # Safety
 * `rom`/`len` must describe a readable buffer that outlives the call.
 */
int32_t rewinds_detect_console(const uint8_t *rom, uintptr_t len);

/**
 * Build a machine. Returns an owning handle (free with [`rewinds_destroy`]) or null
 * on failure, writing a `REWINDS_ERR_*` / `REWINDS_OK` code to `err_out` when non-null.
 *
 * # Safety
 * `cfg` must point to a valid [`RewindsLoad`] whose buffers outlive the call.
 */
RewindsEmulator *rewinds_load(const RewindsLoad *cfg, int32_t *err_out);

/**
 * Free a handle from [`rewinds_load`]. Null is a no-op.
 *
 * # Safety
 * `p` must be null or a handle not used again after this call.
 */
void rewinds_destroy(RewindsEmulator *p);

/**
 * Which console this handle holds ([`REWINDS_CONSOLE_GBA`] / `_NDS`), or `-1` if null.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
int32_t rewinds_console(RewindsEmulator *p);

/**
 * The number of video frames presented so far (0 if null).
 *
 * # Safety
 * `p` must be null or a live handle.
 */
uint64_t rewinds_frame(RewindsEmulator *p);

/**
 * Advance one video frame, presenting the result and feeding audio. A panic in guest
 * code is caught and turns this call into a no-op rather than crossing the boundary.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_run_frame(RewindsEmulator *p);

/**
 * Advance at most `max_cycles` of the current frame, returning an outcome code so a
 * linked host can service its carrier between slices (sub-frame granularity — needed for
 * real-time link, where a game fires many transfers per frame):
 *   `0` frame complete (presented; read screens/audio now),
 *   `1` a serial transfer awaits the peer (exchange a link frame via `rewinds_link_*`
 *       and call again to resume the same frame),
 *   `2` the slice budget was spent mid-frame (call again to continue).
 * With no link carrier attached this never returns `1`, so one call runs a whole frame.
 * A null handle or caught panic returns `0`.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
uint32_t rewinds_run_step(RewindsEmulator *p, uint64_t max_cycles);

/**
 * Re-derive the present buffers from the current framebuffer without advancing
 * (for a repaint after a paused/stepped run).
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_present(RewindsEmulator *p);

/**
 * How many screens this console presents (GBA: 1, NDS: 2; 0 if null).
 *
 * # Safety
 * `p` must be null or a live handle.
 */
uint32_t rewinds_screen_count(RewindsEmulator *p);

/**
 * Fill `out` with the presentable screen at `index` (0 = top). Returns `false` for a
 * null handle, out-of-range index, or null `out`. The `rgba` pointer borrows the
 * emulator — copy it before the next mutating call.
 *
 * # Safety
 * `p` must be null or a live handle; `out` must be null or point to a `RewindsScreen`.
 */
bool rewinds_screen(RewindsEmulator *p, uint32_t index, RewindsScreen *out);

/**
 * Set the input applied on subsequent frames. `buttons` is a mask of `REWINDS_BTN_*`;
 * touch (DS only) is `touch_x`/`touch_y` in bottom-screen pixels with `touch_pressed`.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_set_input(RewindsEmulator *p,
                       uint32_t buttons,
                       int16_t touch_x,
                       int16_t touch_y,
                       bool touch_pressed);

/**
 * Open or close the DS clamshell lid (`closed != 0` shuts it). No-op on the GBA. The
 * host drives this on lifecycle transitions (background/foreground) so the game sleeps.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_set_lid(RewindsEmulator *p, bool closed);

/**
 * Mute audio capture (used for fast-forward): frames still run but drop their samples.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_set_audio_muted(RewindsEmulator *p, bool muted);

/**
 * Attach a host audio output at `rate` Hz with `channels` channels, returning a
 * consumer handle the host drains ([`rewinds_audio_read`]) on its audio thread. Null
 * on a null emulator. Replaces any previous attachment.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
RewindsAudio *rewinds_enable_audio(RewindsEmulator *p, uint32_t rate, uintptr_t channels);

/**
 * Drain up to `capacity` interleaved `f32` samples into `out`, returning how many were
 * written (the caller fills the rest with silence on underrun). Lock-free; safe to call
 * from a real-time audio callback.
 *
 * # Safety
 * `a` must be null or a live audio handle; `out`/`capacity` must describe a writable buffer.
 */
uintptr_t rewinds_audio_read(RewindsAudio *a, float *out, uintptr_t capacity);

/**
 * Free an audio handle from [`rewinds_enable_audio`]. Null is a no-op. Safe to call
 * after the emulator is destroyed (the consumer just underruns).
 *
 * # Safety
 * `a` must be null or a handle not used again after this call.
 */
void rewinds_audio_destroy(RewindsAudio *a);

/**
 * Point `out` at the current battery-save contents (borrowed; copy before the next
 * mutating call). Empty span for a null handle or null `out`.
 *
 * # Safety
 * `p` must be null or a live handle; `out` must be null or point to a `RewindsBytes`.
 */
void rewinds_save_data(RewindsEmulator *p, RewindsBytes *out);

/**
 * Restore previously saved contents (copied in).
 *
 * # Safety
 * `p` must be null or a live handle; `data`/`len` a readable buffer that outlives the call.
 */
void rewinds_load_save_data(RewindsEmulator *p, const uint8_t *data, uintptr_t len);

/**
 * Whether the save changed since the last [`rewinds_clear_save_dirty`] — the host
 * flushes only when this is `true`.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
bool rewinds_save_dirty(RewindsEmulator *p);

/**
 * Acknowledge that the host persisted the current save.
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_clear_save_dirty(RewindsEmulator *p);

/**
 * Configure the serial link: whether a carrier is attached, this unit's id
 * (0 = parent/master, 1-3 = child), and the number of linked units (2-4).
 *
 * # Safety
 * `p` must be null or a live handle.
 */
void rewinds_link_set_config(RewindsEmulator *p, bool connected, uint8_t id, uint8_t count);

/**
 * Take the next serial frame to transmit, writing a borrowed span into `out`
 * (empty when there is nothing to send). The span is valid until the next
 * mutating call; the host copies it before transmitting.
 *
 * # Safety
 * `p` must be null or a live handle; `out` must be non-null and writable.
 */
void rewinds_link_poll_out(RewindsEmulator *p, RewindsBytes *out);

/**
 * Deliver a peer's serial frame received from the carrier.
 *
 * # Safety
 * `p` must be null or a live handle; `bytes`/`len` must describe a readable span
 * that outlives the call.
 */
void rewinds_link_deliver(RewindsEmulator *p, const uint8_t *bytes, uintptr_t len);

/**
 * Whether a serial transfer is in progress (the host should keep pumping).
 *
 * # Safety
 * `p` must be null or a live handle.
 */
bool rewinds_link_pending(RewindsEmulator *p);

/**
 * Write the save type's name (e.g. `"flash128k"`) as UTF-8 (no NUL) into `buf`,
 * returning the number of bytes written (truncated to `cap`). Pass a null `buf` /
 * `cap` of 0 to query the length.
 *
 * # Safety
 * `p` must be null or a live handle; `buf` must be null or point to `cap` writable bytes.
 */
uintptr_t rewinds_save_type_name(RewindsEmulator *p, uint8_t *buf, uintptr_t cap);

/**
 * Override the save type by name (from a host sidecar). Returns `false` for an unknown
 * name, invalid UTF-8, or a console without configurable save types.
 *
 * # Safety
 * `p` must be null or a live handle; `name`/`len` a readable buffer that outlives the call.
 */
bool rewinds_set_save_type_by_name(RewindsEmulator *p, const uint8_t *name, uintptr_t len);

/**
 * The ABI version of this core surface. Bumped when the `rewinds_*` signatures change,
 * so a host can refuse a mismatched framework.
 */
uint32_t rewinds_core_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
